management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

greeting:
  message: Mensagem Lucas

spring:
  data:
    mongodb:
      host: my-release-mongodb.default.svc.cluster.local
      port: 27017
      database: investimento
      username: invests
      password: 1nv35t