management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

greeting:
  message: Mensagem boas vindas

spring:
  data:
    mongodb:
      host: my-release-mongodb.default.svc.cluster.local
      port: 27017
      database: investimento