apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "application.yml" }}
  {{ . }}: |-
    {{- $files.Get . | nindent 4 }}
  {{- end }}