apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodb.name }}
type: Opaque
data:
  spring.data.mongodb.username: {{ .Values.secrets.mongodb.username }}
  spring.data.mongodb.password: {{ .Values.secrets.mongodb.password }}