{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hot-reload-demo-chart.serviceAccountName" . }}
  labels:
    {{- include "hot-reload-demo-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "hot-reload-demo-chart.serviceAccountName" . }}-role
rules:
  - apiGroups:
      - ""
    resources:
      ["*"]
    verbs:
      ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "hot-reload-demo-chart.serviceAccountName" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hot-reload-demo-chart.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "hot-reload-demo-chart.serviceAccountName" . }}